data:
  points_dir: data/points/crop_20um/ds0p25
  raw_A_dir: data/raw/lightsheet_vol_6.9
  raw_b_dir: data/raw/20um_imgs
  downsampling_rate: 0.25
  scale_factor: 8.0
  crop_box_b:
  - 1140
  - 830
  - 1652
  - 1342
  crop_box_A:
  - 5
  - 268
  - 18
  - 69
  - 332
  - 82
  output_dir: result/solve_point/newton_crop_20um_0p25/reg_1.0e-06
  batch_pattern: points_batch_*.pt
  threshold_A: 0.4
  threshold_b: null
solver:
  type: newton
  lambda_reg: 1.0e-06
  n_iter: 35
  positivity: true
  batch_size: 2000
device: cuda
mesh_iso:
- 4.0
